// Generated by Haxe TypeScript Declaration Generator :)

export class C<A, B> {
	f<T>(v: A): B;
}

export namespace ns {
	/**
	 * hi
	 */
	class some {
		/**
		 * hi
		 */
		constructor();
		static f(): void;
	}
}

export class Main {
	/**
	 * ctor doc
	 */
	constructor(name: string, level: number);
	b1: number;
	b2: number;
	readonly b3: number;
	readonly b4: number;
	/**
	 * Do cool stuff
	 */
	some(a: number, b: Main): string;
	static v1: number;
	static v2: number;
	static readonly v3: number;
	static readonly v4: number;
	/**
	 * Some doc
	 */
	static doStuff(debug: boolean): string;
}

export namespace a.b {
	/**
	 * hi
	 */
	function c(): number;
}

export namespace Main {
	/**
	 * bye
	 */
	function g(): number;
}

/**
 * bye
 */
export function some(): number;