// Generated by Haxe 3.4.0 (git build development @ 870b978)
(function ($hx_exports) { "use strict";
var Main = $hx_exports["Main"] = function(name,level) {
	console.log("hi");
};
Main.doStuff = function(debug) {
	return "";
};
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this);
