// Generated by Haxe 3.4.0 (git build development @ 6398c02)
(function ($hx_exports) { "use strict";
$hx_exports["Main"] = $hx_exports["Main"] || {};
$hx_exports["a"] = $hx_exports["a"] || {};
$hx_exports["a"]["b"] = $hx_exports["a"]["b"] || {};
$hx_exports["ns"] = $hx_exports["ns"] || {};
var C = $hx_exports["C"] = function() { };
C.prototype = {
	f: function(v) {
		return null;
	}
};
var Some = $hx_exports["ns"]["some"] = function() {
};
Some.f = function() {
};
var Main = $hx_exports["Main"] = function(name,level) {
	console.log("hi");
};
Main.doStuff = function(debug) {
	return "";
};
Main.f = $hx_exports["a"]["b"]["c"] = function() {
	return 1;
};
Main.g = $hx_exports["Main"]["g"] = function() {
	return 1;
};
Main.h = $hx_exports["some"] = function() {
	return 1;
};
Main.prototype = {
	some: function(a,b) {
		return "";
	}
};
Main.i = 5;
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this);
