// Generated by Haxe TypeScript Declaration Generator :)

declare class Main {
	/**
	 * ctor doc
	 */
	constructor(name: string, level: number);
	b1: number;
	b2: number;
	readonly b3: number;
	readonly b4: number;
	static v1: number;
	static v2: number;
	static readonly v3: number;
	static readonly v4: number;
	/**
	 * Some doc
	 */
	static doStuff(debug: boolean): string;
}